---
name: Release - Preset

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

env:
  DOCKER_BUILD_CHECKS_ANNOTATIONS: false
  DOCKER_BUILD_SUMMARY: false
  DOCKER_BUILD_RECORD_UPLOAD: false

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - os: linux
            platform: amd64
            package: x86_64
          - os: linux
            platform: arm64
            package: aarch64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: src
          push: false
          load: true
          platforms: ${{ matrix.target.os }}/${{ matrix.target.platform }}
          cache-from: type=gha,scope=${{ matrix.target.os }}/${{ matrix.target.platform }}
          cache-to: type=gha,mode=max,scope=${{ matrix.target.os }}/${{ matrix.target.platform }}
          build-args: |
            PLATFORM_OS=${{ matrix.target.os }}
            PLATFORM_ARCH=${{ matrix.target.platform }}
            PACKAGE_ARCH=${{ matrix.target.package }}
          outputs: |
            type=local,dest=dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: preset-${{ matrix.target.os }}-${{ matrix.target.platform }}
          path: "dist/*"

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        platform:
          - os: linux
            platform: amd64
            package: x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: preset-${{ matrix.target.os }}-${{ matrix.target.platform }}
          path: dist

      - name: Test
        run: >-
          make test
          PLATFORM_OS=${{ matrix.target.os }}
          PLATFORM_ARCH=${{ matrix.target.platform }}
          PACKAGE_ARCH=${{ matrix.target.package }}

  release:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    steps:
      - id: prerelease
        run: |
          echo "prerelease=$(if [[ "${{ github.ref }}" == *"-rc"* ]]; then echo "true"; else echo "false"; fi)" >> "$GITHUB_OUTPUT"

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: preset-*

      - name: Create SHA512SUMS
        run: |
          sha512sum preset-* > SHA512SUMS

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ steps.prerelease.outputs.prerelease }}
          generate_release_notes: true
          files: |
            SHA512SUMS
            preset-*
