---
name: Release - Preset

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform:
          - ansible: amd64
            python: x86_64
          - ansible: arm64
            python: aarch64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: >-
          make build
          ANSIBLE_ARCH=${{ matrix.platform.ansible }}
          PYTHON_ARCH=${{ matrix.platform.python }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: preset-linux-${{ matrix.platform.ansible }}
          path: "dist/*"

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        platform:
          - ansible: amd64
            python: x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: preset-linux-${{ matrix.platform.ansible }}
          path: dist

      - name: Test
        run: >-
          make test
          ANSIBLE_ARCH=${{ matrix.platform.ansible }}
          PYTHON_ARCH=${{ matrix.platform.python }}
